### ISSUE TITLE
SpaceSDK Auth Failing

### ISSUE THREAD

**Issue by steven-tomlinson** [lockb0x-llc/lockb0x-ui#17]
Question regarding 2nd step in the following flow
1 : Create Identity in SpaceSDK > Fine
2 : Authenticate with the Space SDK Identity > No user is being returned on authentication and hence it doesn't allow attaching user to space-storage object , following code shows this 

const users = new Users({ endpoint: 'wss://auth-dev.space.storage' });
// createIdentity generate a random keypair identity
const identity = await users.createIdentity();

// the new keypair can be used to authenticate a new user
// `users.authenticate()` generates hub API session tokens for the keypair identity.
const user = await users.authenticate(identity);
// `user` can be used with the storage class to provide identity.

**Tried with both wss endpoints**
> endpoint: 'wss://dev.space.storage'
> endpoint: 'wss://auth-dev.space.storage'

Any idea about this ?

_Originally posted by @bitsworking1690 in https://github.com/lockb0x-llc/lockb0x-ui/issues/7#issuecomment-1234519449_

**Comment by bitsworking1690** [comment]
going to be closed right now in case of decentralized uploading flow.
