### ISSUE TITLE
User must sign in with Freighter in order to Register.

### ISSUE THREAD

**Issue by steven-tomlinson** [lockb0x-llc/lockb0x-ui#22]
Need to verify User is owner of Stellar wallet address using Freighter
Wallet Address text input field should be read-only.
Wallet Address field should only be populated by the address returned from the Freighter sign-in process.

![Image](https://user-images.githubusercontent.com/8976999/188344393-9c17fa91-85ee-4e40-9d95-3023b87fa02b.png)

**Comment by bitsworking1690** [comment]
its unit tested by dev and going to be closed.
